/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#735b25",
        "inverse-surface": "#2f3132",
        "on-tertiary-container": "#848388",
        "on-primary": "#ffffff",
        "surface-variant": "#e2e2e4",
        "inverse-on-surface": "#f0f0f2",
        "outline": "#747878",
        "inverse-primary": "#c8c6c5",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "surface": "#f9f9fb",
        "on-tertiary-fixed": "#1a1b1f",
        "surface-container-highest": "#e2e2e4",
        "tertiary": "#000000",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed-variant": "#474646",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "primary": "#000000",
        "on-secondary": "#ffffff",
        "outline-variant": "#c4c7c7",
        "secondary-container": "#fedb99",
        "error-container": "#ffdad6",
        "surface-container-high": "#e8e8ea",
        "on-surface": "#1a1c1d",
        "secondary-fixed-dim": "#e3c282",
        "primary-container": "#1c1b1b",
        "surface-container": "#eeeef0",
        "on-primary-container": "#858383",
        "primary-fixed": "#e5e2e1",
        "tertiary-container": "#1a1b1f",
        "on-secondary-fixed": "#261a00",
        "on-primary-fixed": "#1c1b1b",
        "on-secondary-container": "#785f29",
        "surface-container-low": "#f3f3f5",
        "on-surface-variant": "#444748",
        "on-secondary-fixed-variant": "#5a430f",
        "background": "#f9f9fb",
        "surface-dim": "#d9dadc",
        "on-tertiary-fixed-variant": "#46464b",
        "secondary-fixed": "#ffdea0",
        "tertiary-fixed": "#e3e2e7",
        "on-background": "#1a1c1d",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c7c6cb",
        "surface-bright": "#f9f9fb",
        "primary-fixed-dim": "#c8c6c5",
        "brand-gold": "#C8A96B",
        "gallery-base": "#F5F5F7",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "160px",
        "container-max": "1440px",
        "margin-desktop": "80px",
        unit: "8px",
        gutter: "32px",
        "margin-tablet": "40px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "display-lg-mobile": ["Hanken Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1440px",
      },
    },
  },
  plugins: [],
};
